# Generated by Django 5.0.2 on 2024-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='From Email')),
                ('to_email', models.EmailField(max_length=254, verbose_name='To Email')),
                ('email_subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('email_body', models.TextField(verbose_name='Email Body')),
            ],
        ),
    ]
